version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "mix"
    directory: "/examples/mist"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "mix"
    directory: "/examples/lustre"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "mix"
    directory: "/examples/wisp"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
